name: flutter_audio
description: A plugin to play mp3 files from local assets.
version: 0.0.1
homepage: https://github.com/chadalen/flutter_audio_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: stellasoft.io.flutter_audio
    pluginClass: FlutterAudioPlugin